name: PrivateStorage
version: ${project.version}
authors: [TheBusyBiscuit, JackStar]
website: https://github.com/TheBusyBiscuit/PrivateStorage

api-version: '1.21'
main: com.github.drakescraft_labs.privatestorage.PrivateStorage

depend:
- Slimefun

permissions:
  PrivateStorage.bypass:
    description: Allows to open all Safes
    default: false
